languages = ["C", "c++", "Java", "Python", "Kotlin", "Javascript"]
print(languages)
languages[-1] = "Hackshell"
print(languages[-4].upper())
msg = f"{languages[3].title()} is my fav language"
print(msg)
languages.append("Rust")
print(languages)
languages.insert(1, "Go")
print(languages)
del languages[1]
print(languages)
print("\nPopped by index: ")
popped_language = languages.pop(1)
print(languages)
print(f"The language {popped_language.title()} is popped from list")
languages.remove("Kotlin")
print(languages)
too_hard = "Java"
languages.remove(too_hard)
print(languages)
print(f"\n{too_hard.title()} is fucking hard to learn")
print(f"The orginal list is: {languages}")
print("\nSorted list by alphabetically: ")
languages.sort()
print(languages)
# print("\nReversed list by alphabetically: ")
# languages.sort(reverse=True)
# print(languages)
# print("\nSorted list by alphabetically: ")
# print(sorted(languages))
# print("\nReversed list by alphabetically: ")
# print(sorted(languages, reverse=True))
# print("\nagain sort list to get back orginal: ")
# print(sorted(languages))
print("\nJust reverse the list: ")
languages.reverse()
print(languages)
print("\nLength of the list: ")
print(len(languages))

